# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gfit_main4.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gfit(object):
    def setupUi(self, Gfit):
        Gfit.setObjectName("Gfit")
        Gfit.setWindowModality(QtCore.Qt.ApplicationModal)
        Gfit.resize(1079, 620)
        self.centralwidget = QtWidgets.QWidget(Gfit)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_Gaussians = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Gaussians.setGeometry(QtCore.QRect(750, 220, 91, 25))
        self.comboBox_Gaussians.setObjectName("comboBox_Gaussians")
        self.pushButton_fit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fit.setGeometry(QtCore.QRect(550, 300, 80, 25))
        self.pushButton_fit.setObjectName("pushButton_fit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 530, 201, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.doubleSpinBox_y_lower = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_y_lower.setObjectName("doubleSpinBox_y_lower")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_y_lower)
        self.doubleSpinBox_y_upper = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_y_upper.setObjectName("doubleSpinBox_y_upper")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_y_upper)
        self.viewer_sum_original = PlotWidget(self.centralwidget)
        self.viewer_sum_original.setGeometry(QtCore.QRect(550, 10, 451, 192))
        self.viewer_sum_original.setObjectName("viewer_sum_original")
        self.viewer_sum_fitted = PlotWidget(self.centralwidget)
        self.viewer_sum_fitted.setGeometry(QtCore.QRect(550, 340, 451, 192))
        self.viewer_sum_fitted.setObjectName("viewer_sum_fitted")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 460, 430, 28))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_52.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_46 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_52.addWidget(self.label_46)
        self.doubleSpinBox_bg_subtract_from = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_bg_subtract_from.setDecimals(3)
        self.doubleSpinBox_bg_subtract_from.setMinimum(-500.0)
        self.doubleSpinBox_bg_subtract_from.setMaximum(500.0)
        self.doubleSpinBox_bg_subtract_from.setProperty("value", -0.1)
        self.doubleSpinBox_bg_subtract_from.setObjectName("doubleSpinBox_bg_subtract_from")
        self.horizontalLayout_52.addWidget(self.doubleSpinBox_bg_subtract_from)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_52.addWidget(self.label_47)
        self.doubleSpinBox_bg_subtract_to = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_bg_subtract_to.setDecimals(3)
        self.doubleSpinBox_bg_subtract_to.setMinimum(-500.0)
        self.doubleSpinBox_bg_subtract_to.setMaximum(500.0)
        self.doubleSpinBox_bg_subtract_to.setProperty("value", 0.0)
        self.doubleSpinBox_bg_subtract_to.setObjectName("doubleSpinBox_bg_subtract_to")
        self.horizontalLayout_52.addWidget(self.doubleSpinBox_bg_subtract_to)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_52.addWidget(self.label_48)
        self.checkBox_subtract_background = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_subtract_background.setObjectName("checkBox_subtract_background")
        self.horizontalLayout_52.addWidget(self.checkBox_subtract_background)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(550, 220, 175, 28))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_number_of_gaussians = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_number_of_gaussians.setMinimum(1)
        self.spinBox_number_of_gaussians.setProperty("value", 1)
        self.spinBox_number_of_gaussians.setObjectName("spinBox_number_of_gaussians")
        self.horizontalLayout.addWidget(self.spinBox_number_of_gaussians)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(550, 260, 251, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.doubleSpinBox_origin = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_origin.setMaximum(999.99)
        self.doubleSpinBox_origin.setObjectName("doubleSpinBox_origin")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_origin)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.doubleSpinBox_fwhm = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_fwhm.setMaximum(999.99)
        self.doubleSpinBox_fwhm.setSingleStep(0.1)
        self.doubleSpinBox_fwhm.setProperty("value", 1.0)
        self.doubleSpinBox_fwhm.setObjectName("doubleSpinBox_fwhm")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_fwhm)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 500, 94, 54))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_sum_x = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_sum_x.setChecked(True)
        self.checkBox_sum_x.setAutoExclusive(True)
        self.checkBox_sum_x.setTristate(False)
        self.checkBox_sum_x.setObjectName("checkBox_sum_x")
        self.verticalLayout.addWidget(self.checkBox_sum_x)
        self.checkBox_sum_y = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_sum_y.setAutoExclusive(True)
        self.checkBox_sum_y.setObjectName("checkBox_sum_y")
        self.verticalLayout.addWidget(self.checkBox_sum_y)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(120, 500, 201, 30))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.doubleSpinBox_x_lower = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinBox_x_lower.setObjectName("doubleSpinBox_x_lower")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_x_lower)
        self.doubleSpinBox_x_upper = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinBox_x_upper.setObjectName("doubleSpinBox_x_upper")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_x_upper)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 531, 441))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.viewer_global_orig_TRPES = GraphicsLayoutWidget(self.tab)
        self.viewer_global_orig_TRPES.setGeometry(QtCore.QRect(0, 40, 521, 361))
        self.viewer_global_orig_TRPES.setObjectName("viewer_global_orig_TRPES")
        self.pushButton_load_csv = QtWidgets.QPushButton(self.tab)
        self.pushButton_load_csv.setGeometry(QtCore.QRect(0, 10, 80, 25))
        self.pushButton_load_csv.setObjectName("pushButton_load_csv")
        self.pushButton_load_sigmas = QtWidgets.QPushButton(self.tab)
        self.pushButton_load_sigmas.setGeometry(QtCore.QRect(90, 10, 80, 25))
        self.pushButton_load_sigmas.setObjectName("pushButton_load_sigmas")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.viewer_global_orig_TRPES_calibrated = GraphicsLayoutWidget(self.tab_2)
        self.viewer_global_orig_TRPES_calibrated.setGeometry(QtCore.QRect(0, 40, 521, 361))
        self.viewer_global_orig_TRPES_calibrated.setObjectName("viewer_global_orig_TRPES_calibrated")
        self.pushButton_plot_calibrated = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_plot_calibrated.setGeometry(QtCore.QRect(0, 10, 115, 28))
        self.pushButton_plot_calibrated.setObjectName("pushButton_plot_calibrated")
        self.tabWidget.addTab(self.tab_2, "")
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(550, 540, 451, 30))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_save_fit = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_save_fit.setObjectName("pushButton_save_fit")
        self.horizontalLayout_5.addWidget(self.pushButton_save_fit)
        self.pushButton_saveCalibration_file = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_saveCalibration_file.setObjectName("pushButton_saveCalibration_file")
        self.horizontalLayout_5.addWidget(self.pushButton_saveCalibration_file)
        self.pushButton_save_trpes = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_save_trpes.setObjectName("pushButton_save_trpes")
        self.horizontalLayout_5.addWidget(self.pushButton_save_trpes)
        self.comboBox_type_gaussian = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_type_gaussian.setGeometry(QtCore.QRect(850, 220, 161, 25))
        self.comboBox_type_gaussian.setObjectName("comboBox_type_gaussian")
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(880, 260, 106, 28))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_range = QtWidgets.QLabel(self.layoutWidget6)
        self.label_range.setObjectName("label_range")
        self.horizontalLayout_8.addWidget(self.label_range)
        self.doubleSpinBox_range = QtWidgets.QDoubleSpinBox(self.layoutWidget6)
        self.doubleSpinBox_range.setMinimum(0.1)
        self.doubleSpinBox_range.setProperty("value", 3.0)
        self.doubleSpinBox_range.setObjectName("doubleSpinBox_range")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_range)
        Gfit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Gfit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1079, 26))
        self.menubar.setObjectName("menubar")
        self.menuoptions = QtWidgets.QMenu(self.menubar)
        self.menuoptions.setObjectName("menuoptions")
        Gfit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Gfit)
        self.statusbar.setObjectName("statusbar")
        Gfit.setStatusBar(self.statusbar)
        self.actionSwitch_TRPES_axis = QtWidgets.QAction(Gfit)
        self.actionSwitch_TRPES_axis.setCheckable(True)
        self.actionSwitch_TRPES_axis.setObjectName("actionSwitch_TRPES_axis")
        self.menuoptions.addAction(self.actionSwitch_TRPES_axis)
        self.menubar.addAction(self.menuoptions.menuAction())

        self.retranslateUi(Gfit)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Gfit)

    def retranslateUi(self, Gfit):
        _translate = QtCore.QCoreApplication.translate
        Gfit.setWindowTitle(_translate("Gfit", "GFit! v 0.5"))
        self.pushButton_fit.setText(_translate("Gfit", "Fit!"))
        self.label_6.setText(_translate("Gfit", "y_limits:"))
        self.label_46.setText(_translate("Gfit", "Subtract as background"))
        self.label_47.setText(_translate("Gfit", "ps to"))
        self.label_48.setText(_translate("Gfit", "ps?"))
        self.checkBox_subtract_background.setText(_translate("Gfit", "yes"))
        self.label.setText(_translate("Gfit", "Number of Gaussians"))
        self.label_2.setText(_translate("Gfit", "origin"))
        self.label_3.setText(_translate("Gfit", "fwhm"))
        self.checkBox_sum_x.setText(_translate("Gfit", "Sum over x"))
        self.checkBox_sum_y.setText(_translate("Gfit", "Sum over y"))
        self.label_5.setText(_translate("Gfit", "x_limits:"))
        self.viewer_global_orig_TRPES.setToolTip(_translate("Gfit", "Scroll pour zoom, \n"
"click on \'A\' in the lower-left corner to get back\n"
" Dragging the lines of the colobar on the right changes the z-scale\n"
"Right Mouse-click for more options (e.g. log-scale of the time-axis)"))
        self.pushButton_load_csv.setText(_translate("Gfit", "Load csv"))
        self.pushButton_load_sigmas.setText(_translate("Gfit", "Load sigmas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Gfit", "Original"))
        self.viewer_global_orig_TRPES_calibrated.setToolTip(_translate("Gfit", "Scroll pour zoom, \n"
"click on \'A\' in the lower-left corner to get back\n"
" Dragging the lines of the colobar on the right changes the z-scale\n"
"Right Mouse-click for more options (e.g. log-scale of the time-axis)"))
        self.pushButton_plot_calibrated.setText(_translate("Gfit", "Calibrate to eV!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Gfit", "Calibrated (for Xenon)"))
        self.pushButton_save_fit.setText(_translate("Gfit", "Save Fit!"))
        self.pushButton_saveCalibration_file.setToolTip(_translate("Gfit", "Assuming you used it on Xenon with two gaussians only"))
        self.pushButton_saveCalibration_file.setText(_translate("Gfit", "Save calibration file"))
        self.pushButton_save_trpes.setText(_translate("Gfit", "Save shown TRPES"))
        self.label_range.setText(_translate("Gfit", "Range"))
        self.menuoptions.setTitle(_translate("Gfit", "options"))
        self.actionSwitch_TRPES_axis.setText(_translate("Gfit", "Switch TRPES axis"))
        self.actionSwitch_TRPES_axis.setShortcut(_translate("Gfit", "Ctrl+S"))
from pyqtgraph import GraphicsLayoutWidget, PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gfit = QtWidgets.QMainWindow()
    ui = Ui_Gfit()
    ui.setupUi(Gfit)
    Gfit.show()
    sys.exit(app.exec_())
